# Generated by Django 5.2.17 on 2026-09-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['fecha', 'id'], 'verbose_name_plural': 'Historial'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-creada_en', '-id'], 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterField(
            model_name='historial',
            name='tipo',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('COMENTARIO', 'Comentario'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CATEGORIA', 'Cambio de categoría'), ('ASIGNACION', 'Asignación')], default='COMENTARIO', max_length=15),
        ),
    ]
