# Generated by Django 5.2.17 on 2026-09-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tipos_de_historial_y_notificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='adjunto',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='prioridad',
        ),
        migrations.AlterField(
            model_name='historial',
            name='tipo',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('COMENTARIO', 'Comentario'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CATEGORIA', 'Cambio de categoría')], default='COMENTARIO', max_length=15),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('NUEVO_TICKET', 'Nuevo ticket'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('COMENTARIO', 'Comentario'), ('TICKET_CERRADO', 'Ticket cerrado')], max_length=20),
        ),
    ]
